//数据图标集
var ProfileJinHuaTable= {
    //剩余换牌道具个数
    //解析背包商品数量
    slot_DBID_BACKPACK_GOODS_COUNT:function(dataTable){
        Profile_JinHuaGameData.readDBID_BACKPACK_GOODS_COUNT(dataTable);
        JinHuaTableLogic.initBackpackGoods();
    },
    //退出房间
    slot_JHID_QUIT_TABLE:function(dataTable){
        Profile_JinHuaGameData.readJHID_QUIT_TABLE(dataTable);
        console.log("退出房间！");
        console.log(dataTable);
    },
    //更新系统公告
    slot_JINHUA_MGR_NOTICE:function(dataTable){
        //牌桌公告
        Profile_JinHuaNotice.readJINHUA_MGR_NOTICE(dataTable);
        JinHuaTableLogic.showNotice();
    },
    //站起
    slot_JHID_STAND_UP:function(dataTable){
        Profile_JinHuaGameData.readJHID_STAND_UP(dataTable);
        JinHuaTableLogic.updateJHID_STAND_UP();
    },
    //坐下
    slot_JHID_SIT_DOWN:function(dataTable){
        console.log("坐下");
        console.log(dataTable);
    },
    //准备
    slot_JHID_READY:function(dataTable){
        Profile_JinHuaGameData.readJHID_READY(dataTable);
        //设置准备
        JinHuaTablePlayer.updateTableAfterPlayerReadyServerBack();
    },
    //请求牌桌在线奖励
    slot_JHID_GET_BAOHE_STEP_INFO:function(dataTable){
        Profile_JinHuaOnlineReward.readJHID_GET_BAOHE_STEP_INFO(dataTable);
        JinHuaTableLogic.updateJHID_GET_BAOHE_STEP_INFO();
    },
    //领取在线时长奖励
    slot_JHID_GET_ONLINE_REWARD:function(dataTable){
        Profile_JinHuaOnlineReward.readJHID_GET_ONLINE_REWARD(dataTable);
        JinHuaTableLogic.updateJHID_GET_ONLINE_REWARD();
    },
    //加注(JHID_BET)
    slot_JHID_BET:function(dataTable){
        console.log("加注");
        console.log(dataTable);
        Profile_JinHuaGameData.readJHID_BET(dataTable);
    },
    //聊天
    slot_JHID_CHAT:function(dataTable){
        Profile_JinHuaGameData.readJHID_CHAT(dataTable);
        JinHuaTableLogic.updateJHID_CHAT();
    },
    //在线时长
    slot_JINHUA_MGR_SETTING:function(dataTable){
        //设置金花数据
        Profile_JinHuaSetting.readJINHUA_MGR_SETTING(dataTable);
        JinHuaTablePlayer.updateAllPlayersLevel();
    }
};
