//金花manager消息
JINHUA_MGR_ID = 0x00680000;
//金花manager消息v4
JINHUA_MGR_ID_V4 = 0x02680000;

//3.10扎金花个人信息消息 (JINHUA_MGR_USER_INFO）
JINHUA_MGR_USER_INFO = JINHUA_MGR_ID_V4 + 10;
//3.05扎金花相关配置请求(JINHUA_MGR_SETTING）
JINHUA_MGR_SETTING = JINHUA_MGR_ID_V4 + 5;
//3.26扎金花每日领工资面板信息 (JINHUA_MGR_DAILY_SALARY）
JINHUA_MGR_DAILY_SALARY = JINHUA_MGR_ID_V4 + 26;
//扎金花领取每日工资 (JINHUA_MGR_GET_SALARY）
JINHUA_MGR_GET_SALARY = JINHUA_MGR_ID + 27;

//3.12金花VIP等级信息 (JINHUA_MGR_VIP_INFO）
JINHUA_MGR_VIP_INFO = JINHUA_MGR_ID + 12;

//3.03扎金花公告记录 (JINHUA_MGR_NOTICE）
JINHUA_MGR_NOTICE = JINHUA_MGR_ID + 3;
//3.46金花背包V2(JINHUA_MGR_BACKPACK_ITEMS_V2）
JINHUA_MGR_BACKPACK_ITEMS_V2 = JINHUA_MGR_ID + 46;


//2.45保险箱info (JHID_STRONG_BOX_INFO)
JHID_STRONG_BOX_INFO = JINHUA_GAME_ID + 45;
//2.46保险箱存钱(JHID_SAVE_TAKE_STRONG_BOX_COIN)
JHID_SAVE_TAKE_STRONG_BOX_COIN = JINHUA_GAME_ID + 46;