//金花manager消息
JINHUA_MGR_ID = 0x00680000;
//金花manager消息v4
JINHUA_MGR_ID_V4 = 0x02680000;

//3.10扎金花个人信息消息 (JINHUA_MGR_USER_INFO）
JINHUA_MGR_USER_INFO = JINHUA_MGR_ID_V4 + 10;
//3.05扎金花相关配置请求(JINHUA_MGR_SETTING）
JINHUA_MGR_SETTING = JINHUA_MGR_ID_V4 + 5;
//3.26扎金花每日领工资面板信息 (JINHUA_MGR_DAILY_SALARY）
JINHUA_MGR_DAILY_SALARY = JINHUA_MGR_ID_V4 + 26;

//金花请求破产送金信息(JINHUA_MGR_REVIVE_INFO)
JINHUA_MGR_REVIVE_INFO = JINHUA_MGR_ID + 1;
//金花请求破产送金 (JINHUA_MGR _REVIVE)
JINHUA_MGR_REVIVE = JINHUA_MGR_ID + 2;
//3.03扎金花公告记录 (JINHUA_MGR_NOTICE）
JINHUA_MGR_NOTICE = JINHUA_MGR_ID + 3;
//3.12金花VIP等级信息 (JINHUA_MGR_VIP_INFO）
JINHUA_MGR_VIP_INFO = JINHUA_MGR_ID + 12;
//金花玩家登录请求领节日礼物 (JINHUA_MGR_JH_ACTIVITY）
JINHUA_MGR_JH_ACTIVITY = JINHUA_MGR_ID + 17;
//金花领取好友签到奖励 (JINHUA_MGR_SIGN_FRIEND_REWARD）
JINHUA_MGR_SIGN_FRIEND_REWARD = JINHUA_MGR_ID + 19;
//扎金花领取每日工资 (JINHUA_MGR_GET_SALARY）
JINHUA_MGR_GET_SALARY = JINHUA_MGR_ID + 27;
//扎金花好友是否有红点 (JINHUA_MGR_FRIEND_HAVE_REDP）
JINHUA_MGR_FRIEND_HAVE_REDP = JINHUA_MGR_ID + 33;
//3.46金花背包V2(JINHUA_MGR_BACKPACK_ITEMS_V2）
JINHUA_MGR_BACKPACK_ITEMS_V2 = JINHUA_MGR_ID + 46;


//2.45保险箱info (JHID_STRONG_BOX_INFO)
JHID_STRONG_BOX_INFO = JINHUA_GAME_ID + 45;
//2.46保险箱存钱(JHID_SAVE_TAKE_STRONG_BOX_COIN)
JHID_SAVE_TAKE_STRONG_BOX_COIN = JINHUA_GAME_ID + 46;
//3.08扎金花好友列表 (JINHUA_MGR_FRIEND_LIST）
JINHUA_MGR_FRIEND_LIST = JINHUA_MGR_ID_V4 + 8;
//3.32扎金花追踪列表 (JINHUA_MGR_TRACE_LIST）
JINHUA_MGR_TRACE_LIST = JINHUA_MGR_ID_V4 + 32;
//3.25扎金花陌生人列表 (JINHUA_MGR_STRANGER_LIST）
JINHUA_MGR_STRANGER_LIST = JINHUA_MGR_ID_V4 + 25;
//扎金花主页活动 (JINHUA_MGR_INDEX_ACTIVITY）
JINHUA_MGR_INDEX_ACTIVITY = JINHUA_MGR_ID_V4 + 48;
//扎金花充值返利相关信息 (JINHUA_MGR_RECHARGE_REBATE_INFO）
JINHUA_MGR_RECHARGE_REBATE_INFO = JINHUA_MGR_ID + 28
////金花房间列表
//JINHUA_ROOMID_ROOM_LIST = JINHUA_ROOM_ID_V4 + 1;